-----------
-- Trait --
-----------
INSERT INTO trait VALUES 
(1,'A l''aise avec les jeunes','MENTAL'),
(2,'Allergique à l''art','MENTAL'),
(3,'Artiste','MENTAL'),
(4,'Avant gardiste','MENTAL'),
(5,'Bricoleurs','MENTAL'),
(6,'Cordon Bleu','MENTAL'),
(7,'Dénicheur','MENTAL'),
(8,'Etourdi','MENTAL'),
(9,'Excentrique','MENTAL'),
(10,'Excité','MENTAL'),
(11,'Fou','MENTAL'),
(12,'Génie','MENTAL'),
(13,'Génie de l''informatique','MENTAL'),
(14,'Instable','MENTAL'),
(15,'Main Verte','MENTAL'),
(16,'Névrosé','MENTAL'),
(17,'Perspicace','MENTAL'),
(18,'Rat de bibliothèque','MENTAL'),
(19,'Sculpteur doué','MENTAL'),
(20,'Virtuose','MENTAL'),
(21,'Œil de photographe','MENTAL'),
(22,'Adore nager','PHYSIQUE'),
(23,'Aime la chaleur','PHYSIQUE'),
(24,'Aime le froid','PHYSIQUE'),
(25,'Athlète','PHYSIQUE'),
(26,'Chanceux','PHYSIQUE'),
(27,'Courageux','PHYSIQUE'),
(28,'Crasseux','PHYSIQUE'),
(29,'Discipliné','PHYSIQUE'),
(30,'Lâche','PHYSIQUE'),
(31,'Maladroit','PHYSIQUE'),
(32,'Malchanceux','PHYSIQUE'),
(33,'Marin','PHYSIQUE'),
(34,'Pantouflard','PHYSIQUE'),
(35,'Peur de l''eau','PHYSIQUE'),
(36,'Pudique','PHYSIQUE'),
(37,'Soigneux','PHYSIQUE'),
(38,'Sommeil lourd','PHYSIQUE'),
(39,'Sommeil léger','PHYSIQUE'),
(40,'Allergique aux enfants','SOCIAL'),
(41,'Amical','SOCIAL'),
(42,'Artiste né','SOCIAL'),
(43,'Aucun sens de l''humour','SOCIAL'),
(44,'Baisers divins','SOCIAL'),
(45,'Charismatique','SOCIAL'),
(46,'Diva','SOCIAL'),
(47,'En pleine introspection','SOCIAL'),
(48,'Enjôleur','SOCIAL'),
(49,'Ermite','SOCIAL'),
(50,'Excessif','SOCIAL'),
(51,'Fan de surnaturel','SOCIAL'),
(52,'Froid','SOCIAL'),
(53,'Fêtard','SOCIAL'),
(54,'Grognon','SOCIAL'),
(55,'Impressionnable','SOCIAL'),
(56,'Incorrect','SOCIAL'),
(57,'Irrésistible','SOCIAL'),
(58,'Loser','SOCIAL'),
(59,'Lèche-bottes','SOCIAL'),
(60,'Mal à l''aise en société','SOCIAL'),
(61,'Mesquin','SOCIAL'),
(62,'Parasite','SOCIAL'),
(63,'Plus que romantique','SOCIAL'),
(64,'Respectable','SOCIAL'),
(65,'Réticent au surnaturel','SOCIAL'),
(66,'Réticent à s''engager','SOCIAL'),
(67,'Sens de l''humour','SOCIAL'),
(68,'Snob','SOCIAL'),
(69,'Timide','SOCIAL'),
(70,'Ultrasociable','SOCIAL'),
(71,'Vendeur né','SOCIAL'),
(72,'Aime les animaux','STYLE_VIE'),
(73,'Aime les chats','STYLE_VIE'),
(74,'Aime les chiens','STYLE_VIE'),
(75,'Allergique à la nature','STYLE_VIE'),
(76,'Ambitieux','STYLE_VIE'),
(77,'Amoureux de la nature','STYLE_VIE'),
(78,'Aventureux','STYLE_VIE'),
(79,'Bienveillant','STYLE_VIE'),
(80,'Bourreau de travail','STYLE_VIE'),
(81,'Casse-cou','STYLE_VIE'),
(82,'Cavalier','STYLE_VIE'),
(83,'Ecolo','STYLE_VIE'),
(84,'Econome','STYLE_VIE'),
(85,'Fan de robots','STYLE_VIE'),
(86,'Grand gamin','STYLE_VIE'),
(87,'Hypersensible','STYLE_VIE'),
(88,'Kleptomane','STYLE_VIE'),
(89,'Malveillant','STYLE_VIE'),
(90,'Oiseau de nuit','STYLE_VIE'),
(91,'Passionné d''automobile','STYLE_VIE'),
(92,'Perfectionniste','STYLE_VIE'),
(93,'Pêcheur','STYLE_VIE'),
(94,'Rebelle','STYLE_VIE'),
(95,'Sang chaud','STYLE_VIE'),
(96,'Star par nature','STYLE_VIE'),
(97,'Technophobe','STYLE_VIE'),
(98,'Tourné vers la famille','STYLE_VIE'),
(99,'Végétarien','STYLE_VIE');

-------------
-- Souhait --
-------------

INSERT INTO souhait VALUES 
(1,'Acteur Superstar'),
(2,'Artisan alchimiste'),
(3,'Artiste de rue crédible'),
(4,'Artiste du blog'),
(5,'As du design interieur'),
(6,'Auteur professionnel'),
(7,'Bourreau des cœurs'),
(8,'Casanova'),
(9,'Chef de la meute'),
(10,'Chirurgien de renommée mondiale'),
(11,'Collectionneur high-tech'),
(12,'Compagnon des chiens'),
(13,'Compositeur de bande originale'),
(14,'Créateur de monstres'),
(15,'Création d''arche'),
(16,'Créer le parfait aquarium privé'),
(17,'Célèbre chef cinq étoiles'),
(18,'Des mots et des doigts en or'),
(19,'Descendant de Da Vinci'),
(20,'Devenir astronaute'),
(21,'Devenir le roi des voleurs'),
(22,'Devenir un athlète superstar'),
(23,'Devenir éleveur de cyborgs'),
(24,'Dirigeant du monde libre'),
(25,'Détective privé omniprésent'),
(26,'Empire hôtelier'),
(27,'Entouré par une famille'),
(28,'Espion international'),
(29,'Etudiant magistral'),
(30,'Etudiant parfait'),
(31,'Extrêmement populaire'),
(32,'Fan de félins'),
(33,'Galerie de niveau mondial'),
(34,'Grand acrobate'),
(35,'Grand explorateur'),
(36,'Grand magicien'),
(37,'Illustre auteur'),
(38,'Jardins plus verts'),
(39,'Jockey'),
(40,'L''empereur du mal'),
(41,'La vie des VIP'),
(42,'Le sim-orchestre'),
(43,'Le bibliothécaire culinaire'),
(44,'Le jardin parfait'),
(45,'Légende des échecs'),
(46,'Légende vocale'),
(47,'Maître des arts martiaux'),
(48,'Maître du mysticisme'),
(49,'Mixologue magistral'),
(50,'Musée privé'),
(51,'Médium pour célébrités'),
(52,'Obtenir une influence maximale sur tous les groupes sociaux'),
(53,'Opportuniste'),
(54,'PDG dune multinationale'),
(55,'Perfection physique'),
(56,'Plongeur des profondeurs'),
(57,'Plus qu''une machine'),
(58,'Prendre du bon temps'),
(59,'Pro du paranormal'),
(60,'Protection d''animaux'),
(61,'Présentateur des actualités '),
(62,'Relooking magique'),
(63,'Rock star'),
(64,'Réalisateur reconnu'),
(65,'Sauveteur de bord de mer'),
(66,'Si j''ai un objet dans la main il est à moi'),
(67,'Sim au multiples talents'),
(68,'Soigneur mystique'),
(69,'Spécialiste des arts'),
(70,'Spécialiste des licornes'),
(71,'Spécialiste en médecine légale'),
(72,'Spécialiste scientifique'),
(73,'Superhéros des pompiers'),
(74,'Transformer la ville'),
(75,'Un esprit parfait dans un corps parfait'),
(76,'Une cave à nectar sans fond'),
(77,'Visionnaire'),
(78,'Vivre dans le grand luxe'),
(79,'Voyageur expérimenté'),
(80,'Zombificateur magistral'),
(81,'Zoologiste');

INSERT INTO classe VALUES 
(1,'Illégitime',NULL),
(2,'Paysan',3),
(3,'Pauvre',4),
(4,'Modeste',5),
(5,'Aisée',6),
(6,'Riche',7),
(7,'Noblesse',NULL);
